---
title: "plot_assignment"
output: html_notebook
---


Subletting data


```{r}

# Clean the data, change the data type from Char to Date, time, num 
# save the subset to a sparate file for later procesing
library(data.table)
library(sqldf)

# define start date or end date
sdate <- as.Date("01/02/2007",format ="%d/%m/%Y")
edate <- as.Date("02/02/2007",format ="%d/%m/%Y")

numnames = c("Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")

# read and subset the data with sdata, and edate
df=fread("household_power_consumption.txt",na.strings="?")

# change char to IDate and Itime type for later processing
df<- df[, ("Date") := lapply(.SD, as.Date, format ="%d/%m/%Y"), .SDcols = "Date"]
df<-df[, ("Time") := lapply(.SD, as.ITime), .SDcols = "Time"]

#subsetting data, save the usefule bit
dt <- subset(df, df$Date %between% c(sdate,edate))

#set numnames to be numeric for later works 
dt<- dt[, (numnames) := lapply(.SD, as.numeric), .SDcols = numnames]
dt<-dt[complete.cases(dt),]
# create a smaller text file to work on 
fwrite(dt,"workingData.csv")

```


Plot 1 

```{r}
library(data.table)
# read small Data set
dt <-fread("workingData.csv")

# plotting with hist 
with(dt, hist(Global_active_power, 
              main = "Global Active power",
              col = "red",
              xlab = "Global Active power(kilowatts)"))

# copy to file
dev.copy(png,"plot1.png")
dev.off()

```



Plot 2

```{r}
library(data.table)

# read small Data set
dt <-fread("workingData.csv")

dt[, ("Time") := lapply(.SD, as.ITime), .SDcols = "Time"]

head(dt)

dnt <- as.POSIXct(paste(dt$Date,dt$Time), format = "%Y-%m-%d %H:%M:%S")
dt$DnT <- dnt
# plotting with hist 
with(dt, plot(DnT,Global_active_power,type = "l",
              ylab = "Global Active power(kilowatts)",
              xlab = ""))
head(dt)
# copy to file
dev.copy(png,"plot2.png")
dev.off()


```


Plot 3 

```{r}

library(data.table)

# read small Data set
dt <-fread("workingData.csv")
  

# need to make it bigger..
png("plot3.png", width = 600, height = 600)

with(dt,plot(DnT,Sub_metering_1,type = "l",col = "black",xlab = "", ylab = "Energy sub metering"))
with(dt,lines(DnT,Sub_metering_2, col = "red"))
with(dt,lines(DnT,Sub_metering_3, col = "blue"))

legend("topright", pch =1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))


# copy to file
#dev.copy(png,"plot3.png", width=10, height=10)
dev.off()


```
```{r}

library(data.table)

# read small Data set
dt <-fread("workingData.csv")
png("plot4.png", width = 800, height = 800)
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))


with(dt, {
  
  plot(DnT,Global_active_power,type = "l",
              ylab = "Global Active power(kilowatts)",
              xlab = "")
  
  plot(DnT,Voltage,type = "l",
              ylab = "Voltage",
              xlab = "datetime")
  
  
  plot(DnT,Sub_metering_1,type = "l",col = "black",xlab = "", ylab = "Energy sub metering")
  lines(DnT,Sub_metering_2, col = "red")
  lines(DnT,Sub_metering_3, col = "blue")
  legend("topright", pch =1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  
  
  plot(DnT,Global_reactive_power,type = "l",
              ylab = "Global_reactive_power",
              xlab = "datetime")
 
  #mtext("ozone and weahter", outer = T)
  }
  
)

dev.off()

```

